export default {
  HOME: "/",
  BASE_URL: "/api/",
  REGISTER: "/api/auth/register/",
  LOGIN: "/api/auth/login/",
  PRODUCTS: "/products/",
  PRODUCT_DETAIL: "/product-detail/",
  BASKET: "/basket/",
  ADDRESSES: "/addresses/addresses/",
  ADDRESS: "/address",
  ADDRESS_LIST: "/address-list",
  COUNTRIES: "/addresses/countries/",
  CITIES: "/addresses/cities/",
  TOWNSHIPS: "/addresses/townships/",
  CHECKOUT: "/checkout",
  SET_ADDRESS: "/checkout/set_address/",
};
