export default {
  HOME: "/",
  BASE_URL: "/api/",
  REGISTER: "/api/auth/register/",
  LOGIN: "/api/auth/login/",
  PRODUCTS: "/products/",
  PRODUCT_DETAIL: "/product-detail/",
  BASKET: "/basket/",
  ADDRESSES: "/addresses/addresses/",
  ADDRESS: "/address",
  ADDRESS_LIST: "/address-list",
  COUNTRIES: "/addresses/countries/",
  CITIES: "/addresses/cities/",
  TOWNSHIPS: "/addresses/townships/",
  CHECKOUT: "/checkout",
  SET_ADDRESS: "/checkout/set_address/",
  SET_PAYMENT: "/checkout/set_payment_option/",
  SET_SHIPPING: "/checkout/set_shipping_option/",
  SET_DISCOUNT: "/checkout/set_discount_code/",
  COMPLETE_ORDER: "/checkout/complete_order/",
};
